rush01/hi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

urlpatterns = [
    # path('', include('test.urls')),
    path('', include('low.urls')),
    path('admin/', admin.site.urls),

    # path('publishers/', PublisherListView.as_view(), name = 'publishers'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rush01/low/rush01/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('', include('test.urls')),
    path('', include('ex.urls')),
    path('admin/', admin.site.urls),

    # path('publishers/', PublisherListView.as_view(), name = 'publishers'),
] 

rush01/low/urls.py
from django.urls import path
from .views import * 

from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
# from .views import TipCreateView, TipListView, TipDeleteView
urlpatterns = [

    path('articles/', ArticleListView.as_view(), name = 'articles'),
    path('', ArticleRedirectView.as_view(), name = 'index'),
    path('login/', Login.as_view(), name = 'login'),
    path('register/', Registration.as_view(), name = 'register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('publications/', Publications.as_view(), name='publications'),
    path(
        "articles/<int:article_id>/",
        Detail.as_view(),
        name="detail",
    ),
    path('favourite/', Favourites.as_view(), name='favourite'),
    path('publish/', Publish.as_view(), name='publish'),
    path('articles/<int:article_id>/comment/', Detail.as_view(), name="create_comment"),
    path('articles/<int:article_id>/comment/<int:comment_id>', Recomment.as_view(), name="recomment"),
    # path('profile/', Profile_view.as_view(), name='profile'),
    path('profile/', Profile.as_view(), name='profile'),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rush01/low/models/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User
# from ..forms.comment import CommentForm

class Article(models.Model) :
    title = models.CharField(max_length=64, null=False)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE, null=False)
    created = models.DateTimeField(auto_now=True, auto_now_add=False)
    synopsis = models.CharField(max_length=312, null=False)
    content = models.TextField(null=False)

    def __str__(self):
        return self.title

class UserFavouriteArticle(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE, null=False)
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE, null=False)
    
    def __str__(self):
        return self.article.title

class Comment(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE, null=False)
    content = models.TextField('reple')
    create_date = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

class ReComment(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE, null=False)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now=True)
    comment_id = models.ForeignKey(Comment, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    def get_replay(self):
        from ex.forms.comment import CommentForm
        form = CommentForm()
        form.feilds['id'] = self.id
        return form

class Profile(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE, null=False, primary_key=True)
    name = models.CharField(max_length=64, null=False)
    surname = models.CharField(max_length=64, null=False)
    email = models.EmailField(null=False)
    description = models.TextField(null=False)
    picture = models.ImageField(blank=True, upload_to="images", null=True)

rush01/low/forms/PublishForm.py
from django import forms
from django.forms.widgets import Textarea


class PublishForm(forms.Form):
    title = forms.CharField(max_length=64, required=True)
    synopsis = forms.CharField(max_length=312, required=True)
    content = forms.CharField(widget=Textarea(), required=True)

rush01/low/forms/comment.py
from ..models.models import Comment
from django import forms

class CommentForm(forms.Form):
    model = Comment
    content = forms.CharField(required=True)

rush01/low/forms/favourite.py
from typing import Any, Mapping, Optional, Type, Union
from django import forms
from django.forms.utils import ErrorList
from django.forms.widgets import HiddenInput, Textarea


class FavouriteForm(forms.Form):
    article = forms.IntegerField(widget=HiddenInput(), required=True)

    def __init__(self, article, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        if article is not None:
            self.fields['article'].initial = article

rush01/low/views.py
from django.shortcuts import render

# Create your views here.

rush01/low/views/article_list.py
# views.py
from django.views.generic import ListView
from low.models.models import Article
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    # context_object_name = 'article_list.html'
    template_name = 'article_list.html'
    paginate_by = 10
    queryset = Article.objects.all().order_by('-created')
    login_url = reverse_lazy('login')

rush01/low/views/detail.py
from django.views.generic import DetailView, FormView
from ..models.models import Article,Comment
from typing import Any
from django import http
from django.http.response import HttpResponseBase
from ..forms.favourite import FavouriteForm
from ..forms.comment import CommentForm
from django.views.generic import DetailView
from django.urls import reverse_lazy, reverse
from django.db import DatabaseError
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin


class Detail(DetailView, FormView):
    template_name = "detail.html"
    form_class = CommentForm
    model = Article
    pk_url_kwarg = 'article_id'
    def get_success_url(self): 
        return reverse('detail', args=[self.kwargs.get(self.pk_url_kwarg)])
        # return reverse('detail', kwargs={'pk': self.kwargs.get(self.pk_url_kwarg)})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = context['object']
        context["favouriteForm"] = FavouriteForm(article.id)
        context["comment_form"] = CommentForm
        return context

    def form_valid(self, form:CommentForm):
        content = form.cleaned_data['content']
        try:
            Comment.objects.create(
                content=content,
                author=self.request.user,
                article_id=self.kwargs.get(self.pk_url_kwarg)
                # 아티클 아이디 갖고오기. 개쩔어ㅓ
            )
        except DatabaseError as e:
            messages.error(
                self.request, "Unsuccessful comment. DatabaseError")
            messages.error(self.request,e)
            return redirect('index')
        messages.success(self.request, "Successful comment.")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(
            self.request, "Unsuccessful Comment. Invalid information.")
        return super().form_invalid(form)

rush01/low/views/favourite.py
from django.views.generic import ListView, FormView
from ..models.models import Article, UserFavouriteArticle 

from django.db.models.query import QuerySet
from django.forms.forms import BaseForm
from django.db import DatabaseError
from django.contrib.auth.mixins import LoginRequiredMixin
from ..forms.favourite import FavouriteForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy


class Favourites(LoginRequiredMixin, ListView, FormView):
    template_name = "favourite.html"
    form_class = FavouriteForm
    success_url = reverse_lazy('index')
    login_url = reverse_lazy('login')
    model: UserFavouriteArticle = UserFavouriteArticle

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def form_valid(self, form: AuthenticationForm):
        article_id = form.cleaned_data['article']
        try:
            UserFavouriteArticle.objects.get(
                article=article_id, user=self.request.user).delete()
            messages.success(
                self.request, "successful Remove to favourite.")
        except UserFavouriteArticle.DoesNotExist as e:
            try:
                UserFavouriteArticle.objects.create(
                    user=self.request.user,
                    article=Article.objects.get(id=article_id),
                )
                messages.success(
                    self.request, "successful Add to favourite.")
            except DatabaseError as e:
                messages.error(
                    self.request, "Unsuccessful Add to favourite. Database error.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Unsuccessful Add to favourite. Invalid information.")
        return super().form_invalid(form)

    def get_form(self, form_class=None) -> BaseForm:
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(None, **self.get_form_kwargs())

rush01/low/views/index.py
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy

class ArticleRedirectView(RedirectView):
    # url = 'http://127.0.0.1:8000/articles'
    url = reverse_lazy('articles')
    

rush01/low/views/login.py
from ..forms.login import LoginForm
from typing import Any
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpRequest
from django.shortcuts import redirect
from django.views.generic import FormView
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

class Login(FormView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = reverse_lazy('index')
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return (redirect('index'))
        return super().get(request, *args, **kwargs)
    def form_valid(self, form: LoginForm):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=username, password=password)
        if user is None:
            messages.error(self.request, "Invalid username or password.")
            return
        login(self.request, user)
        messages.info(self.request, f"You are now logged in as {username}.")
        return super().form_valid(form)
    def form_invalid(self, form):
        return super().form_invalid(form)

rush01/low/views/logout.py
from django.views.generic import RedirectView
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect

class Logout(RedirectView):
    url = "index.html"

    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect('index')

rush01/low/views/profile.py
from django.http import request
from ..models import models
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import DatabaseError
from django.shortcuts import redirect
from ..forms.profile import ProfileForm
from django.views.generic import FormView,DetailView
from django.contrib.auth import login
from django.contrib import messages
from django.urls import reverse_lazy


class Profile(LoginRequiredMixin, FormView):
    template_name = "profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy('profile')

    def get_initial(self):
        try:
            user = models.Profile.objects.get(user_id=self.request.user.id)
            self.initial = {
                "name": user.name,
                "surname": user.surname,
                "email": user.email,
                "description": user.description,
                "picture": user.picture,
            }
            return self.initial.copy()
        except Exception as e:
            models.Profile.objects.create(
                user=self.request.user,
                name="",
                surname="",
                email="",
                description="",
                picture=None
            )
            redirect('profile')
    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.user_id = self.request.user.id
        profile.save()
        return super().form_valid(form)

    # def form_valid(self, form: ProfileForm):
    #     name = form.cleaned_data['name']
    #     surname = form.cleaned_data['surname']
    #     email = form.cleaned_data['email']
    #     description = form.cleaned_data['description']
    #     picture = form.cleaned_data['picture']
    #     try:
    #         models.Profile.objects.create(
    #             user=self.request.user,
    #             name=name,
    #             surname=surname,
    #             email=email,./m
    #             description=description,
    #             picture=picture
    #         )
            
    #     except DatabaseError as e:
    #         messages.success(
    #             self.request, "Unsuccessful make profile. DatabaseError")
    #         return redirect('index')
    #     messages.success(self.request, "Successful make profile.")
    #     return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Unsuccessful profile. Invalid information.")
        return super().form_invalid(form)

rush01/low/views/publications.py
# views.py
from django.views.generic import ListView
from ..models.models import Article 
from django.contrib.auth.mixins import LoginRequiredMixin

class Publications(LoginRequiredMixin, ListView):
    model = Article
    # context_object_name = 'article_list.html'
    template_name = 'article_list.html'

    def get_queryset(self):
        print(self.request.user)
        return Article.objects.all().filter(author=self.request.user).order_by('-created')
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

rush01/low/views/recomment.py
from django.views.generic import FormView
from ..models.models import Article,Comment,ReComment
from ..forms.comment import CommentForm
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect

class Recomment(FormView):
    template_name = "detail.html"
    form_class = CommentForm
    model = Comment
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('detail', args=[self.kwargs.get('article_id')])

    def form_valid(self, form:CommentForm):
        content = form.cleaned_data['content']
        try:
            parent= Comment.objects.get(pk=self.kwargs.get(self.pk_url_kwarg))
        except Comment.DoesNotExist:
            messages.error(
                self.request, "Unsuccessful comment. Nothing Comment")
            return redirect('index')
        try:
            ReComment.objects.create(
                content=content,
                author=self.request.user,
                comment_id=parent
            )

        except DatabaseError as e:
            messages.error(
                self.request, "Unsuccessful comment. DatabaseError")
            messages.error(self.request,e)
            return redirect('index')
        messages.success(self.request, "Successful comment.")
        return super().form_valid(form)
            
    def form_invalid(self, form):
        messages.error(
            self.request, "Unsuccessful Comment. Invalid information.")
        return redirect('detail', self.kwargs.get('article_id'))

rush01/low/views/registration.py
from django.views.generic import FormView
from django.contrib.auth import login
from django.contrib import messages
from django.urls import reverse_lazy
from ..forms.newuserform import NewUserForm
from django.shortcuts import redirect
from ..models import models


class Registration(FormView):
    template_name = "registration.html"
    form_class = NewUserForm
    success_url = reverse_lazy('index')
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return (redirect('index'))
        return super().get(request, *args, **kwargs)
     
    def form_valid(self, form: NewUserForm):
        user = form.save()
        login(self.request, user)
        models.Profile.objects.create(
                user=self.request.user,
                name="",
                surname="",
                email="",
                description="",
                picture=None
            )

        messages.success(self.request, "Registration successful.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Unsuccessful registration. Invalid information.")
        return super().form_invalid(form)

rush01/low/templates/article_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Synopsis</th>
            <th>Writer</th>
            <th>Created</th>
            <th>When</th>
            <th> </th>
            <!-- <th>content</th> -->
        </tr>

        {% for publisher in object_list %}
        <tr>
            <td>{{ publisher.title|truncatechars:20 }}</td>
            <td>{{ publisher.synopsis|truncatechars:20 }}</td>
            <td>{{ publisher.author }}</td>
            <td>{{ publisher.created }}</td>
            <td>{{ publisher.created|timesince}}</td>
            <td>
                {% buttons %}
                <a href="{% url 'articles' %}{{ publisher.id }}"  class="btn btn-danger">
                  Read
                </a>
                {% endbuttons %}
            </td>
            <!-- <td>{{ publisher.content }}</td> -->
        </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
    {% endif %}


{% endblock %}

rush01/low/templates/base.html
{% load static %} {% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BitCoin</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        #login_form label {
            display: none;
            }
        
        .nav li:hover{
            background-color: black;
        }
        body {
            background: rgb(217,169,82)
        }
    </style>
</head>
<body >
<div style="background-image: url('https://www.google.com/url?sa=i&url=http%3A%2F%2Fm.coinreaders.com%2F10869&psig=AOvVaw0i7pQyqMUnAoX5fAjq3ZuD&ust=1623173456148000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOj2tbyGhvECFQAAAAAdAAAAABAD');">
        {% bootstrap_messages %}
<div class='container'>
    <a href="{% url 'index' %}"><h2 style="display: inline-block; color:black">Doge <h3 style="display: inline-block; margin-left:1vw; color:rgb(125,125,125);" > to the Moon</h3></h2></a>
    {% include 'nav.html' %}
</div>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>
</div>
</body>
</html>

rush01/low/templates/detail.html
{% extends 'base.html' %} {% load bootstrap3 %}

{% block title %}{{ object.title }} | {% endblock title %}

{% block content %}
<div>
  <h1>{{ object.title }}</h1>
  <div style="display: flex; justify-content: space-between;">
    <div>
      <h3 style="display: inline-flex; color: rgb(125, 125, 125)">
        {{ object.author }}
      </h3>
      <h5 style="display: inline-flex">- {{ object.created }}</h5>
    </div>
    {% if user.is_authenticated %}
    <form style="display: inline-flex; 	align-self: center;" action="{% url 'favourite' %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form favouriteForm %}
      {% buttons submit='🔖' %}{% endbuttons %}
    </form>
    {% endif %}
  </div>
  <hr />
  <div class="lead">
    <blockquote>{{ object.synopsis }}</blockquote>
    <div>{{ object.content }}</div>
  </div>
  {% if user.is_authenticated %}

  <form method="post" class="form" action="{% url 'create_comment' article.id %}">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}    
  </form>
        {% endif %}

  {% for reple in article.comment_set.all %}
    <div style="margin-left:30px">
      <p><h4> {{reple}}</h4></p><p><h6>{{reple.author}}</h6></p>
      <p><h6>{{reple.create_date}}</h6></p>
      <hr>

        {% for r in reple.recomment_set.all %}
        <div style="margin-left:60px">
          <p><h4> {{r}}</h4></p><p><h6>{{r.author}}</h6></p>
          <p><h6>{{r.create_date}}</h6></p>
        </div>
        {% endfor %}
        {% if user.is_authenticated %}
        <form method="post" class="form" action="{% url 'recomment' article.id reple.id %}" style="margin-left:30px">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}    
        </form> 
        {% endif %}
    </div>
  {% endfor %}
</div>
{% endblock %}

rush01/low/templates/favourite.html
{% extends 'base.html' %} {% load bootstrap3 %}
{% block title %}Favourite | {% endblock title %}
{% block content %}

<div>
  <h1 style="display: inline-block">Favourite</h1>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>Title</th>
      </tr>
      {% for favourite in object_list %}
      <tr>
        <td>
          <a
            href="{% url 'articles' %}{{ favourite.article.id }}"
            >{{ favourite.article.title }}</a
          >
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

rush01/low/templates/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Login | {% endblock %}

{% block content %}
<div>
  <h1>Login</h1>
  <form action="{% url 'login' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons class="btn btn-info" submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>
</div>
{% endblock content %}

rush01/low/templates/nav.html
{% load static %} {% load bootstrap3 %}
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <!-- 메뉴에서 가장 왼쪽, 모바일에서5 표시되는 제목 -->
    <div class="navbar-header">
      <!-- 모바일때 표시되는 메뉴 버튼(PC 버젼에서는 보이지 않는다.) -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}"></a>
</div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      <ul class="nav navbar-nav navbar-left" >
      <li class="navbar-brand">
          <a href="{% url 'index' %}" style="padding:0%;margin-left:5px">
              <span style="margin-left:-22px; font-size:20px" class="glyphicon glyphicon-bitcoin" aria-hidden="true"></span><span class="sr-only">(current)</span></a>
      </li>
     {% if user.is_authenticated %}
      <li>
          <a href="{% url 'articles' %} ">Articles <span class="sr-only"></span></a>
      </li>
      <li >
        <a href="{% url 'publish' %}">Publish <span class="sr-only"></span></a>
      </li>
      <li >
        <a href="{% url 'favourite' %}">Favourites <span class="sr-only"></span></a>
      </li>
      <li >
        <a href="{% url 'profile' %}">Profile <span class="sr-only"></span></a>
      </li>
      <li>
        <a href="{% url 'publications' %}">Publications <span class="sr-only"></span></a>
      </li>
      {% else %}
      <li>
          <a href="{% url 'register' %}">Register <span class="sr-only"></span></a>
      </li>
      {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            {% if user.is_staff %}
            <li>
              <a href="{% url 'admin:index' %}"><h5 style="color:red">STAFF</h5></a>
            </li>
            {% endif %}
            <li >
              <a href="#">Logged as {{request.user.username}}<span class="sr-only"></span></a>
            </li>
            <li >
              <a href="{% url 'logout' %}">Logout<span class="sr-only"></span></a>
            </li>
            {% else %}
            <li>
            <form id="login_form" action="{% url 'login' %}" class="navbar-form navbar-left" method="POST">
                {% csrf_token %}
                {% bootstrap_form login_form %}
                {% buttons %}
                <button type="submit" class="btn btn-default">Login</button>
                {% endbuttons %}
              </form>
            </li>
            {% endif %}
              </ul>
            </li>
      </ul>
    </div>
  </div>
</nav>

rush01/low/templates/profile.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Profile | {% endblock %}

{% block content %}
<div>
  <h1>Profile</h1>
  <form action="{% url 'profile' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if profile.photo %}
      <img src="{{ profile.photo.url }}" >
    {% endif %}
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>
</div>
{% endblock content %}

rush01/low/templates/publish.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Publish | {% endblock %}

{% block content %}
<div>
  <h1>Publish</h1>
  <form action="{% url 'publish' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success" >OK</button>
    <button type="reset" class="btn btn-default" >Cancle</button>
    <!-- {% buttons submit='OK' reset="Cancle" %}{% endbuttons %} -->
  </form>
</div>
{% endblock content %}

rush01/low/templates/registration.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %} 


<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Submit
      </button>
    {% endbuttons %}
</form>

{% endblock %}